org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.222
neo_version_range=[21.1.0,)
loader_version_range=[1,)

mod_id=extraspeciallib
mod_name=ExtraSpecialLIB
mod_license=MIT
mod_version=1.0.1
mod_group_id=uk.co.extraspecialstudio
mod_authors=Extra_Special_K / TWGMike / Manialate
mod_description=ES Library (ESL) - shared backend foundation for Extra Special Studio mods. No GUI.
